import streamlit as st

st.title("Rock AC")
st.header("HOME 2001")
st.image(r"albums/DISC 1 HOM M3/FIRE IN YOUR HEART - front.jpg")
st.subheader("RAIN FOREST")
st.audio(r"albums/DISC 1 HOM M3/A1-RAIN FOREST acbbg.mp3")
st.subheader("FIRST TIMER")
st.audio(r"albums/DISC 1 HOM M3/A2-FIRST TIMER  acbbg.mp3")
st.subheader("REPRODUCTION")
st.audio(r"albums/DISC 1 HOM M3/A3-REPRODUCTION acbbg.mp3")
st.subheader("LOTTO")
st.audio(r"albums/DISC 1 HOM M3/A4-LOTTO  acbbg.mp3")
st.subheader("TANIT")
st.audio(r"albums/DISC 1 HOM M3/A5-TANIT  acbbg.mp3")
st.subheader("YOU ARE MY SUNSHINE")
st.audio(r"albums/DISC 1 HOM M3/A6-YOU ARE MY SUNSHINE acbbg.mp3")
st.subheader("THE WEIGHT OF A TON")
st.audio(r"albums/DISC 1 HOM M3/A7- THE WEIGHT OF A TON acbbg.mp3")
st.subheader("GIGOLO")
st.audio(r"albums/DISC 1 HOM M3/A8- GIGOLO acbbg.mp3")
st.subheader("BRIDGE BLUES")
st.audio(r"albums/DISC 1 HOM M3/A9- BRIDGE BLUES acbbg.mp3")
st.subheader("SYLENT WATCHER")
st.audio(r"albums/DISC 1 HOM M3/A10- SYLENT WATCHER acbbg.mp3")